# Generated by Django 4.1.4 on 2023-03-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_post_movie_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='First_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Last_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
