# Generated by Django 4.1.4 on 2023-03-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_post_created_at_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at_str',
        ),
    ]
